Wed Mar 06 19:16:57 COT 2019 : Servidor de red Apache Derby: Se ha iniciado 10.10.2.0 - (1582446) y está listo para aceptar las conexiones en el puerto 1527
----------------------------------------------------------------
Wed Mar 06 19:16:58 COT 2019:
 Iniciando instancia a816c00e-0169-5582-9c71-000019b96758 de Derby, versión The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): 
en el directorio de base de datos C:\Users\jerso\Desktop\POO\Proyecto\POOComercial\DatosPOO con el cargador de clases sun.misc.Launcher$AppClassLoader@1d44bcfa
Cargado desde file:/C:/Program%20Files/glassfish-4.1.1/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_181-b13
user.dir=C:\Program Files\glassfish-4.1.1\javadb
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\jerso\Desktop\POO\Proyecto\POOComercial
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Wed Mar 06 19:17:06 COT 2019:
Cerrando la instancia a816c00e-0169-5582-9c71-000019b96758 en el directorio de base de datos C:\Users\jerso\Desktop\POO\Proyecto\POOComercial\DatosPOO con cargador de clases sun.misc.Launcher$AppClassLoader@1d44bcfa
Wed Mar 06 19:17:06 COT 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = DatosPOO), (DRDAID = {2}), Cierre de la base de datos 'DatosPOO'.
----------------------------------------------------------------
Wed Mar 06 19:18:11 COT 2019:
 Iniciando instancia 560740aa-0169-5582-9c71-000019b96758 de Derby, versión The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): 
en el directorio de base de datos C:\Users\jerso\Desktop\POO\Proyecto\POOComercial\DatosPOO con el cargador de clases sun.misc.Launcher$AppClassLoader@1d44bcfa
Cargado desde file:/C:/Program%20Files/glassfish-4.1.1/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_181-b13
user.dir=C:\Program Files\glassfish-4.1.1\javadb
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\jerso\Desktop\POO\Proyecto\POOComercial
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Wed Mar 06 20:06:04 COT 2019 Thread[DRDAConnThread_3,5,main] (XID = 379), (SESSIONID = 2), (DATABASE = DatosPOO), (DRDAID = {4}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Mar 06 20:06:04 COT 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = DatosPOO), (DRDAID = {4}), Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
----------------------------------------------------------------
Wed Mar 06 20:06:45 COT 2019: cerrando motor de Derby
